### ISSUE TITLE
SQL Injections

### ISSUE THREAD

**Issue by arnerak** [HelipengTony/olog#2]
Hello,
your code is prone to SQL injections, since user input is not escaped. For example:
https://github.com/HelipengTony/olog/blob/master/log/view.php#L20

You can use prepared statements or escape user input before inserting it into SQL queries.
For example, please consider using `mysqli_real_escape_string($con,$_GET['view'])`.

**Comment by ttttonyhe** [comment]
Hi,
Thanks for noticing. I am preparing to rebuild the entire program, and I will fix the bugs all together at the time.
